
FROM ufoym/deepo:caffe-py36-cu80



RUN pip3 install \
    imutils==0.5.2 \
    pyzmq==18.0.1

COPY . /home/deepframework/descriptor/emotion_detection
COPY --from=utils:deep_setup /home/deepframework/utils/. /home/deepframework/descriptor/utils
COPY --from=agent:deep_setup /home/deepframework/agent/. /home/deepframework/descriptor



WORKDIR /home/deepframework/descriptor


CMD python sub_agent.py

