services:
    clothing_broker:
        environment:
        - FP_ADDRESS=person_detector_detector
        - BROKER_NAME=clothing_broker
        - BROKER_PORT=6000
        - FP_OUT=5001
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/broker:deep
        networks:
        - net_deep
    clothing_sub_collector:
        environment:
        - COLLECTOR_ADDRESS=person_detector_collector
        - SUB_COL_PORT=6050
        - COL_PORT=7000
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/sub_collector:deep
        networks:
        - net_deep
    clothing_descriptor:
        environment:
        - MODE=cpu
        - FRAMEWORK=tensorflow
        - BROKER_ADDRESS=clothing_broker
        - SUB_COLLECTOR_ADDRESS=clothing_sub_collector
        - MONITOR_ADDRESS=monitor
        - MONITOR_STATS_IN=5550
        - GPU_ID=None
        - BROKER_PORT=6000
        - SUB_COL_PORT=6050
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/clothing:deep_cpu
        networks:
        - net_deep
    person_detector_detector:
        environment:
        - COLLECTOR_ADDRESS=person_detector_collector
        - VIDEOSRC_ADDRESS=stream_manager
        - MONITOR_ADDRESS=monitor
        - STREAM_OUT=3500
        - FP_OUT=5001
        - FP_OUT_TO_COL=4001
        - MONITOR_STATS_IN=5550
        - GPU_ID=None
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/person_detector:deep_cpu
        networks:
        - net_deep
        deploy:
            placement:
                constraints:
                - node.hostname==linuxkit-025000000001
    person_detector_collector:
        environment:
        - PROV_OUT_TO_COL=4001
        - OUT_STREAM_PORT=7050
        - OUT_SERVER_PORT=4050
        - MONITOR_STATS_IN=5550
        - STREAM_MANAGER_ADDRESS=stream_manager
        - SERVER_ADDRESS=server
        - MONITOR_ADDRESS=monitor
        - COMPONENT_NAME=person_detector_collector
        - ALGS=clothing:7000
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/collector:deep
        networks:
        - net_deep
    stream_manager:
        environment:
        - HP_SERVER=server
        - COLLECTOR_PORTS=7050
        - SERVER_PORT=8000
        - STREAM_OUT=3500
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/stream_manager:deep
        networks:
        - net_deep
        depends_on:
        - server
    stream_capture_stand:
        environment:
        - HP_SERVER=server
        - SERVER_PORT=8000
        - STREAM_CAPTURE_ID=stand
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/stream_capture:deep
        networks:
        - net_deep
        depends_on:
        - server
        volumes:
        - deep_media_volume:/mnt/remote_media
    stream_capture_inc:
        environment:
        - HP_SERVER=server
        - SERVER_PORT=8000
        - STREAM_CAPTURE_ID=inc
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/stream_capture:deep
        networks:
        - net_deep
        depends_on:
        - server
        volumes:
        - deep_media_volume:/mnt/remote_media
    monitor:
        environment:
        - ALGS=clothing
        - MONITOR_STATS_IN=5550
        - MONITOR_STATS_OUT=5551
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/monitor:deep
        networks:
        - net_deep
    server:
        environment:
        - COLLECTOR_PORTS=4050
        - MONITOR_STATS_OUT=5551
        - MONITOR_ADDRESS=monitor
        - SERVER_PORT=8000
        - ALGS=clothing
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/server:deep
        networks:
        - net_deep
        ports:
        - 8000:8000
version: '3'
volumes:
    deep_media_volume:
        external: true
networks:
    net_deep:
