services:
    gender_broker:
        environment:
        - FP_ADDRESS=face_detector_detector
        - BROKER_NAME=gender_broker
        - BROKER_PORT=6000
        - FP_OUT=5001
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/broker:deep
        networks:
        - net_deep
    gender_sub_collector:
        environment:
        - COLLECTOR_ADDRESS=face_detector_collector
        - SUB_COL_PORT=6050
        - COL_PORT=7000
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/sub_collector:deep
        networks:
        - net_deep
    gender_descriptor:
        environment:
        - MODE=cpu
        - FRAMEWORK=caffe
        - BROKER_ADDRESS=gender_broker
        - SUB_COLLECTOR_ADDRESS=gender_sub_collector
        - MONITOR_ADDRESS=monitor
        - MONITOR_STATS_IN=5550
        - GPU_ID=None
        - BROKER_PORT=6000
        - SUB_COL_PORT=6050
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/gender:deep_cpu
        networks:
        - net_deep
    face_detector_detector:
        environment:
        - COLLECTOR_ADDRESS=face_detector_collector
        - VIDEOSRC_ADDRESS=stream_manager
        - MONITOR_ADDRESS=monitor
        - STREAM_OUT=3500
        - FP_OUT=5001
        - FP_OUT_TO_COL=4001
        - MONITOR_STATS_IN=5550
        - GPU_ID=None
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/face_detector:deep_cpu
        networks:
        - net_deep
        deploy:
            placement:
                constraints:
                - node.hostname==linuxkit-025000000001
    face_detector_collector:
        environment:
        - PROV_OUT_TO_COL=4001
        - OUT_STREAM_PORT=7050
        - OUT_SERVER_PORT=4050
        - MONITOR_STATS_IN=5550
        - STREAM_MANAGER_ADDRESS=stream_manager
        - SERVER_ADDRESS=server
        - MONITOR_ADDRESS=monitor
        - COMPONENT_NAME=face_detector_collector
        - ALGS=gender:7000
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/collector:deep
        networks:
        - net_deep
    stream_manager:
        environment:
        - HP_SERVER=server
        - COLLECTOR_PORTS=7050
        - SERVER_PORT=8000
        - STREAM_OUT=3500
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/stream_manager:deep
        networks:
        - net_deep
        depends_on:
        - server
    monitor:
        environment:
        - ALGS=gender
        - MONITOR_STATS_IN=5550
        - MONITOR_STATS_OUT=5551
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/monitor:deep
        networks:
        - net_deep
    server:
        environment:
        - COLLECTOR_PORTS=4050
        - MONITOR_STATS_OUT=5551
        - MONITOR_ADDRESS=monitor
        - SERVER_PORT=8000
        - ALGS=gender
        env_file:
        - env_params.list
        image: 192.168.195.224:5000/server:deep
        networks:
        - net_deep
        ports:
        - 8000:8000
version: '3'
volumes:
    deep_media_volume:
        external: true
networks:
    net_deep:
