
FROM tensorflow/tensorflow:1.12.3-py3


RUN apt-get update && apt-get install -y \ 
    build-essential \
    libjpeg-dev \
    libopencv-dev \
    pkg-config \
    iputils-ping \
    python-setuptools

RUN pip3 install \
    pyzmq==18.0.1 \
    opencv-python==4.1.0.25 \
    keras==2.2.4 \
    pyyaml==5.1.1

COPY . /home/deepframework/descriptor/face_recognition
COPY --from=utils:deep_setup /home/deepframework/utils/. /home/deepframework/descriptor/utils
COPY --from=agent:deep_setup /home/deepframework/agent/. /home/deepframework/descriptor

COPY --from=face_recognition:deep_setup /home/deepframework/descriptor/face_recognition/template_models/. /home/deepframework/descriptor/face_recognition/template_models

COPY --from=face_recognition:deep_setup /home/deepframework/descriptor/face_recognition/facenet/src/models/20170131-234652/. /home/deepframework/descriptor/face_recognition/facenet/src/models/20170131-234652

COPY --from=descriptor_tests:deep_setup /home/deepframework/descriptor_tests/execute_test.py /home/deepframework/descriptor


WORKDIR /home/deepframework/descriptor


CMD python3 sub_agent.py



