

FROM sample:cpu



RUN pip3 install \
    imutils==0.5.2 \
    pyzmq==18.0.1 \
    opencv-python==4.1.0.25 \
    opencv-contrib-python==4.2.0.34



COPY . /home/deepframework/detector/sample_detector

COPY --from=utils:deep_setup /home/deepframework/utils /home/deepframework/detector/sample_detector/utils
COPY --from=interface:deep_setup /home/deepframework/interface/. /home/deepframework/detector/sample_detector


WORKDIR /home/deepframework/detector/sample_detector

CMD python3 provider.py
