
FROM tensorflow/tensorflow:1.12.0-gpu-py3



RUN apt-get update && apt-get install -y \ 
    build-essential \
    libjpeg-dev \
    libopencv-dev \
    pkg-config \
    iputils-ping \
    python-setuptools

RUN pip3 install \
    pyzmq \
    opencv-python \
    keras \
    pyyaml



COPY . /home/deepframework/descriptor/clothing_recognition
COPY --from=utils:deep_setup /home/deepframework/utils /home/deepframework/descriptor/utils
COPY --from=agent:deep_setup /home/deepframework/agent/. /home/deepframework/descriptor
COPY --from=descriptor_tests:deep_setup /home/deepframework/descriptor_tests/execute_test.py /home/deepframework/descriptor



WORKDIR /home/deepframework/descriptor



