FROM tensorflow/tensorflow:latest-py3


RUN apt-get update && apt-get install -y \ 
    build-essential \
    libjpeg-dev \
    libopencv-dev \
    pkg-config \
    iputils-ping \
    python-setuptools

RUN pip3 install \
    pyzmq \
    opencv-python \
    keras

COPY . /home/deepframework/descriptor/clothing_recognition
COPY --from=utils:deep /home/deepframework/utils /home/deepframework/descriptor/utils
COPY --from=agent:deep /home/deepframework/agent/. /home/deepframework/descriptor



WORKDIR /home/deepframework/descriptor



