
FROM python:3.7-slim


RUN apt-get update && apt-get install -y \ 
    build-essential \
    libjpeg-dev \
    libopencv-dev \
    pkg-config \
    iputils-ping \
    python-setuptools \
    ntpdate

RUN pip3 install \
    pyzmq \
    opencv-python

COPY . /home/deepframework/monitor
COPY --from=utils:deep /home/deepframework/utils /home/deepframework/monitor/utils

WORKDIR /home/deepframework/monitor

CMD python monitor.py